# Generated by Django 5.2.5 on 2025-08-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_alter_item_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
