# Generated by Django 5.2.5 on 2025-08-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_alter_list_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
