# Generated by Django 5.2.5 on 2025-08-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_list_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="list",
            field=models.TextField(default=""),
        ),
    ]
